version: '3.8'
services:
  redis:
    image: redis:7.0.2
    volumes:
      - redisdata:/data
    ports:
      - 6379:6379
    command: redis-server --save 60 1 --loglevel warning
volumes:
  redisdata: