patch: "D:\\tmp\\techLogData\\log"
redis_addr: "localhost:6379"
redis_login: ""
redis_password: ""
elastic_addr: "http://localhost:9200"
elastic_login: ""
elastic_password: ""
tech_log_details_events: "Context|Txt|Descr|DeadlockConnectionIntersections"
patch_logfile: "./logs/"
log_level: 1
maxdop: 4