# Расположение логов тех журнала 1С
patch: "D:\\tmp\\1"
#
# Параметры подключения к Redis
redis_addr: "localhost:6379"
redis_login: ""
redis_password: ""
#
# Параметры подключения к Elasticsearch
elastic_addr: "http://localhost:9200"
elastic_login: ""
elastic_password: ""
#
# Правила формирования индекса Elasticsearch
# Пример: "tech_journal_yyyyMMddhh" в конце к имени индекса всегда добавляется имя процесса, например rphost_11212 
elastic_indx: "tech_journal_yyyyMMddhh"
#
# Типы событий тех журнала, которые могут содержать длинные строки '...' и переносы строк \n
tech_log_details_events: "Context|Txt|Descr|DeadlockConnectionIntersections"
#
# Путь, где будут распологаться логи программы
patch_logfile: "D:\\tmp\\techLogData\\log"
#
# Глубина фиксации ошибок при работе программы:
#   1 - только ошибки
#   2 - ошибки и предупреждения 
#   3 - ошибки, предупреждения и информация
log_level: 1
#
# Уровень параллелизма
maxdop: 1